
from pyscriptic import settings, submit

class RunProperties(object):
    """

    Attributes
    ----------
    run_id : str
    title : str
    created_at : ...
    status : str
    protocol : pyscriptic.protocols.Protocol
    """
    def __init__(self, run_id, title, created_at, status, protocol):
        self.run_id = run_id
        self.title = title
        self.created_at = created_at
        self.status = status
        self.protocol = protocol

def run(request, title="PyTranscript Run"):
    """
    Submits a run request for the currently active project. The request should
    be in the form of a json description of the low or high-level protocol.

    Parameters
    ----------
    request : dict
    title : str, optional

    Returns
    -------
    run_id : str
    """

    url = "{}/{}/runs".format(
        settings.get_organization(),
        settings.get_project(),
        )
    content = {
        "title": title,
        "request": request,
        }
    run_id = submit.post_request(
        url,
        content,
        )["id"]
    return run_id

def get_run(run_id):
    """
    Gets information about a single run within the currently active project.

    Parameters
    ----------
    run_id : str

    Returns
    -------
    ...
    """
    url = "{}/{}/runs/{}".format(
        settings.get_organization(),
        settings.get_project(),
        run_id,
        )
    return submit.get_request(
        url,
        )

def list_runs():
    """
    Lists all runs for the currently active project.

    Returns
    -------
    list of dict of str, str
    """
    return project.get_project(settings.get_project()).runs

def get_run_data(run_id):
    """
    Get data generated by a given run.

    Parameters
    ----------
    run_id : str

    Returns
    -------
    ...
    """
    url = "{}/{}/runs/{}/data".format(
        settings.get_organization(),
        settings.get_project(),
        run_id,
        )
    return submit.get_request(
        url,
        )

# Get monitoring data (Coming soon)
